project: 
  type: website
  output-dir: docs

website:
  title: "Natalie Cann Data Analysis Portfolio"
  navbar:
    left:
      - text: "About Me"
        file: aboutme.qmd
      - text: "Projects"
        menu:
          - text: "Starter Analysis Exercise"
            file: starter-analysis-exercise/products/report/starter-analysis-report.qmd
          - text: "R Coding Exercise"
            file: coding-exercise/coding-exercise.qmd
          - text: "Data Exercise"
            file: data-exercise/data-exercise.qmd
          - text: "Data Analysis Exercise"
            file: cdcdata-exercise/cdcdata-exercise.qmd
          - text: "Presentation Exercise"
            file: presentation-exercise/presentation-exercise.qmd
          - text: "Fitting Exercise"
            file: fitting-exercise/fitting-exercise.qmd
          - text: "Machine Learning"
            file: ml-models-exercise/ml-models-exercise.qmd
          - text: "Tidy Tuesday"
            file: tidytuesday-exercise/tidytuesday-exercise.qmd
          - text: "Course Project"
            file: course-project/Project-Manuscript.qmd
          - text: "Course Project - Supplementary Material"
            file: course-project/Supplementary-Material.qmd

    right:
      - icon: github 
        href: https://github.com/NatalieCann16/nataliecann-MADA-portfolio        
format:
  html:
    theme: journal
    highlight: zenburn
    css: styles.css
    toc: FALSE